trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Image to ACR'
  inputs:
    containerRegistryType: 'Azure Container Registry'
    azureSubscription: 'Azure-Cloud-Connection'
    azureContainerRegistry: 'sakshicr2026'
    repository: 'devops-container-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
