trigger:
- main

pool:
  name: 'Default'

steps:
- script: |
    docker build -t sakshicr2026.azurecr.io/devops-container-project:latest .
    docker push sakshicr2026.azurecr.io/devops-container-project:latest
  displayName: 'Build and Push Image'
